### ISSUE TITLE
New questions

### ISSUE THREAD

**Issue by yyEudora** [MMorafah/PACFL#4]
Hello, Dr. MMorafah,
Recently I found a bug in the main_pacfl.py file of unseen_clients, lines 564 to 579, where the best training accuracy is saved in the clients_best_acc list, which makes the test accuracy of the new client model saved as 100%, so in the end the average test accuracy of all clients is more than 89% of the average accuracy rate mentioned in the paper. In fact, the accuracy is not up to the accuracy mentioned in the paper, right?

**Comment by MMorafah** [comment]
Hello,

Thanks for mentioning. The training accuracy was being stored in the clients_best_acc_list. I have fixed that part now. This wouldn’t affect the results we reported in the paper since we have reported the final accuracy not the best accuracy.

Regards,
Mahdi

**Comment by yyEudora** [comment]
> Hello, Thanks for mentioning. The training accuracy was being stored in the clients_best_acc_list. I have fixed that part now. This wouldn’t affect the results we reported in the paper since we have reported the final accuracy not the best accuracy. Regards, Mahdi
> […](#)
> On Aug 4, 2023 at 12:24 AM -0700, yyEudora ***@***.***>, wrote: Hello, Dr. MMorafah, Recently I found a bug in the main_pacfl.py file of unseen_clients, lines 564 to 579, where the best training accuracy is saved in the clients_best_acc list, which makes the test accuracy of the new client model saved as 100%, so in the end the average test accuracy of all clients is more than 89% of the average accuracy rate mentioned in the paper. In fact, the accuracy is not up to the accuracy mentioned in the paper, right? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you for your warmly reply！
