### ISSUE TITLE
Questions about the model used in your paper

### ISSUE THREAD

**Issue by yangwentong** [MMorafah/PACFL#5]
Hello, I saw in the experimental section of Chapter 3 of your paper that your three data sets FMNIST, SVHN and CIFAR-10 use the LeNet-5 model, but I did not find it in your code ( Your code uses simple-cnn for CIFAR-10). What does this part mean?

**Comment by MMorafah** [comment]
Hello,

Thank you for your interest in our work. simple-cnn is the lenet-5 model.

**Comment by yangwentong** [comment]
Thank you for answering my question. But now when I reproduce the paper, when I run the **pacfl.sh** file under the scripts folder in your code, the results obtained are different from the final results written in your paper. Can you provide the hyperparameter settings at that time?

**Comment by yangwentong** [comment]
> Hello, Thank you for your interest in our work. simple-cnn is the lenet-5 model.
> […](#)
> On Dec 10, 2023 at 10:52 PM -0800, yangwentong ***@***.***>, wrote: Hello, I saw in the experimental section of Chapter 3 of your paper that your three data sets FMNIST, SVHN and CIFAR-10 use the LeNet-5 model, but I did not find it in your code ( Your code uses simple-cnn for CIFAR-10). What does this part mean? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


Thank you for answering my question. 
But now when I reproduce the paper, when I run the pacfl.sh file under the scripts folder in your code, the results obtained are different from the final results written in your paper. Can you provide the hyperparameter settings at that time?

**Comment by yangwentong** [comment]
> Hello, Thank you for your interest in our work. simple-cnn is the lenet-5 model.
> […](#)
> On Dec 10, 2023 at 10:52 PM -0800, yangwentong ***@***.***>, wrote: Hello, I saw in the experimental section of Chapter 3 of your paper that your three data sets FMNIST, SVHN and CIFAR-10 use the LeNet-5 model, but I did not find it in your code ( Your code uses simple-cnn for CIFAR-10). What does this part mean? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you for answering my question.
But now when I reproduce the paper, when I run the **pacfl.sh** file under the scripts folder in your code, the results obtained are different from the final results written in your paper. Can you provide the hyperparameter settings at that time?
**(Under the skew (20%) for non-IID tags, the accuracy of the data set CIFAR-10 in your paper is 89.30 ± 0.41, but the results of my own multiple runs are somewhat different from this.)**

**Comment by MMorafah** [comment]
Hello,

The hyperparameters are discussed in the paper. Probably you need to tune the clustering threshold in your data partitioning. Fix the set of clients data partitioning and then run some ablations for the clustering threshold. Typically, a 2-4 clusters for CIFAR-10 gets good results.

**Comment by yangwentong** [comment]
> Hello, The hyperparameters are discussed in the paper. Probably you need to tune the clustering threshold in your data partitioning. Fix the set of clients data partitioning and then run some ablations for the clustering threshold. Typically, a 2-4 clusters for CIFAR-10 gets good results.
> 你好，
> 
> 论文中讨论了超参数。您可能需要调整数据分区中的聚类阈值。修复客户端数据分区集，然后针对集群阈值运行一些消融。通常，CIFAR-10 的 2-4 个聚类可以获得良好的结果。
> […](#)
> On Dec 12, 2023 at 6:44 AM -0800, yangwentong ***@***.***>, wrote: > Hello, Thank you for your interest in our work. simple-cnn is the lenet-5 model. > … > On Dec 10, 2023 at 10:52 PM -0800, yangwentong @.>, wrote: Hello, I saw in the experimental section of Chapter 3 of your paper that your three data sets FMNIST, SVHN and CIFAR-10 use the LeNet-5 model, but I did not find it in your code ( Your code uses simple-cnn for CIFAR-10). What does this part mean? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> Thank you for answering my question. But now when I reproduce the paper, when I run the pacfl.sh file under the scripts folder in your code, the results obtained are different from the final results written in your paper. Can you provide the hyperparameter settings at that time? (Under the skew (20%) for non-IID tags, the accuracy of the data set CIFAR-10 in your paper is 89.30 ± 0.41, but the results of my own multiple runs are somewhat different from this.) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>


Thank you
