### ISSUE TITLE
A missing directory called initialization

### ISSUE THREAD

**Issue by MrezaSherkati** [MMorafah/PACFL#6]
Hello.

I hope you are doing well.

I am trying to run your mix4 code, but in the main_pacfl_mix4 script, there are a few lines of code which access several files in a directory named initialization. Unfortunately I cannot find this directory. I was wondering if you could help me with this.

Thank you very much for your help.

**Comment by MMorafah** [comment]
Hello,

Thanks for your interest in our work. The initialization was just a saved random initialization of the model and clients partitioning. I think in the code those lines are comment. If not, you can either try commenting those lines or create and save the initializations.

Regards,
Mahdi

**Comment by MrezaSherkati** [comment]
Thank you very much for your warm response.

**Comment by MMorafah** [comment]
No problem, thank you for your interest in our work. Please feel free to reach out if there was further comments or discussions.

Regards,
Mahdi

**Comment by MrezaSherkati** [comment]
Hello,

I hope you are doing well.

Sorry to bother you again regarding another issue. I am running your code for the 20% non-IID scenario for the CIFAR100 and I am using resnet-9 as the model based on your paper. The results that I am receiving after 50 communication rounds is way higher than the results in your paper. I am receiving an accuracy around 91.7%. This accuracy is the average of the accuracy of the clients' models on their local testset.

I would appreciate it if you could help me with this.

Regards,
Mohammadreza

**Comment by MMorafah** [comment]
Hello,

I think if the difference within range of +- 6%, it could be random seed, that’s why it’s important to using different random seeds and getting the average results. For best practices it’s better to fixate the data partitioning of the clients, and then experimenting with different random seed for the initialization of the model and calculating the average results for more robust performance evaluation. I hope this helps!

Please feel free to reach out if you had further questions.

Regards,
Mahdi

**Comment by MrezaSherkati** [comment]
Thank you for your response. I appreciate it.

I see. I am also trying to test the model using different random seeds. I will try fixating the data partitioning of the clients to see if this makes any difference.

Just to confirm, is it correct to first do the federation and after the federation, clients test their last version of their local model on their local test set and we take the average of these accuracies across all the clients?

Best,
Mohammadreza

**Comment by MMorafah** [comment]
Yes, it’s correct.

You can also check my recent paper on FL evaluation and experimental design: https://ieeexplore.ieee.org/abstract/document/10189084

Regards,
Mahdi

**Comment by MrezaSherkati** [comment]
Thank you very much for your fast response. I really appreciate your time and effort for answering my questions.

Thank you very much for sharing your recent paper with me. I will check it out.

Best regards,
Mohammadreza
