### ISSUE TITLE
Question about test results.

### ISSUE THREAD

**Issue by Hexiao13** [MMorafah/PACFL#7]
In an algorithm that utilizes a global model, such as FedAvg (Federated Averaging), the final test result is typically the average performance of all locally trained models tested on the global model.These are the test results under two labels.
Train Loss: 0.016770239107586966, Test_loss: 0.913794419817224
Train Acc: 99.3469009399414, Test Acc: 83.67900085449219
Best Clients AVG Acc: 84.98799896240234
Global Model Test Acc: 31.400, Global Model Best Test Acc: 38.440
**Is Global Model Best Test Acc: 38.440?**
In using a personalized algorithm, such as IFCA (Individual Fairness Constrained Algorithm), the final test result is typically the result of testing each individual model on the personalized algorithm.These are the test results under two labels.
Train Loss: 0.38491460177811176, Test_loss: 0.45683930942506074
Train Acc: 83.65840148925781, Test Acc: 80.51748657226562
Best Clients AVG Acc: 83.4419937133789
Best Global Model Acc: 40.959999084472656
Train Loss: 0.3041259425247284, Test_loss: 0.39850053844727573
Train Acc: 87.11293029785156, Test Acc: 83.06500244140625
Best Clients AVG Acc: 86.03700256347656
Best Global Model Acc: 45.060001373291016
**Is Best Clients AVG Acc: 83.4419937133789**

**Comment by lemontree888** [comment]
？
